PACKAGE_FORMAT = "!{flag}{id}|x{content}"

DATA_FORMAT = "%3.3f"

DELAY_FORMAT = "{delay}"

CONNECTION_FLAG = "CO"
RECIEVED_FLAG = "RE"
TRANSMISSION_FLAG = "TR"

SPREADING_FREQUENCY = 7
BANDWIDTH = 125
CODING_RATE = 2
MAX_PACKET_SIZE = 64
NUM_OF_NODES = 2
BASE_DELAY = 2000

# maximum airtime per node = 1 minute = 60000 ms