PACKAGE_FORMAT = "!{flag}{id}|x{content}"

DATA_FORMAT = "%3.3f"

DELAY_FORMAT = "{delay}"

CONNECTION_FLAG = "CO"
RECIEVED_FLAG = "RE"
TRANSMISSION_FLAG = "TR"

SPREADING_FREQUENCY = 6
BANDWIDTH = 100
CODING_RATE = 50
MAX_PACKET_SIZE = 32
NUM_OF_NODES = 2
BASE_DELAY = 2000